import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "./_components/navbar";

import DefaultUserIcon from 'public/default-user-icon-white.png'

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  const name = "Joe Smith";
  const userIcon = "";

  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Navbar username={name} imageUrl={userIcon ? userIcon : DefaultUserIcon}/>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
